name: Ruby Gem

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    steps:
      - uses: actions/checkout@master
      - run: |
          gem update bundler
          ./bundler_version.sh
          bundle install
          bundle exec rake rubocop
  test:
    name: Build + Publish
    runs-on: ubuntu-latest
    container:
      image: ruby:${{ matrix.ruby_version }}
      env:
        BUNDLE_GEMFILE: $PWD/gemfiles/${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby_version:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
        gemfile:
          - gemfiles/faraday_15.gemfile
          - gemfiles/faraday.gemfile
          - gemfiles/sequel4.gemfile
          - gemfiles/sequel5.gemfile
          - gemfiles/sinatra.gemfile
          - gemfiles/rack.gemfile
          - gemfiles/rails_41.gemfile
          - gemfiles/rails_42.gemfile
          - gemfiles/rails_5.gemfile
          - gemfiles/rails_51.gemfile
          - gemfiles/rails_52.gemfile
          - gemfiles/rails_6.gemfile
    steps:
      - uses: actions/checkout@master
      - run: |
          gem update bundler
          ./bundler_version.sh
          bundle install
          bundle exec rake test
          
